controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello_world_bundle:
    resource:
        path: ../src/HelloWorldBundle/Controller/
        namespace: App\HelloWorldBundle\Controller
    type: attribute
