imports:
    - { resource: '../src/AG/RepoStatusBundle/Resources/config/services.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies based on type hints
        autoconfigure: true # Automatically registers services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
