parameters:
    github_owner: '%env(GITHUB_OWNER)%'
    github_repo: '%env(GITHUB_REPO)%'
    gitlab_owner: '%env(GITLAB_OWNER)%'
    gitlab_repo: '%env(GITLAB_REPO)%'
    bitbucket_owner: '%env(BITBUCKET_OWNER)%'
    bitbucket_repo: '%env(BITBUCKET_REPO)%'

imports:
    - { resource: '../src/RepoStatusBundle/Resources/config/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $owner: '%github_owner%'
            $repo: '%github_repo%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
