# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ConfigurationService:
        arguments:
            $filePath: '%kernel.project_dir%/config/config.yaml'

    App\Repository\GitHubRepository:
        arguments:
            $config: '@=service("App\Service\ConfigurationService").getRepositoryConfig()'

    App\Repository\GitLabRepository:
        arguments:
            $config: '@=service("App\Service\ConfigurationService").getRepositoryConfig()'

    App\Repository\BitbucketRepository:
        arguments:
            $config: '@=service("App\Service\ConfigurationService").getRepositoryConfig()'

    App\Notification\SlackNotification:
        arguments:
            $config: '@=service("App\Service\ConfigurationService").getNotificationConfig()'

    App\Command\CheckRepositoryStatusCommand:
        arguments:
            $configService: '@App\Service\ConfigurationService'
            $repository: '@App\Repository\GitHubRepository' # Change this based on the repository type
            $notification: '@App\Notification\SlackNotification'
        tags: ['console.command']
