imports:
    - { resource: '../src/RepoStatusBundle/Resources/config/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $owner: '%github.owner%'
            $repo: '%github.repo%'
            $baseUrl: '%github.api_base_url%'
            $slackBotToken: '%slack.bot_token%'
            $slackChannel: '%slack.channel%'
            $slackApiBaseUrl: '%slack.api_base_url%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Automatically register and tag all classes that implement QuestionInterface
    App\RepoStatusBundle\Question\:
        resource: '../src/RepoStatusBundle/Question/*'
        tags: ['app.question']

    App\RepoStatusBundle\Service\QuestionCollector:
        arguments:
            $questions: !tagged_iterator 'app.question'
