parameters:
    github_owner: '%env(GITHUB_OWNER)%'
    github_repo: '%env(GITHUB_REPO)%'
    gitlab_owner: '%env(GITLAB_OWNER)%'
    gitlab_repo: '%env(GITLAB_REPO)%'
    bitbucket_owner: '%env(BITBUCKET_OWNER)%'
    bitbucket_repo: '%env(BITBUCKET_REPO)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    AG\RepoStatusBundle\Config\GitHubConfig:
        arguments:
            $owner: '%github_owner%'
            $repo: '%github_repo%'

    AG\RepoStatusBundle\Config\GitLabConfig:
        arguments:
            $owner: '%gitlab_owner%'
            $repo: '%gitlab_repo%'

    AG\RepoStatusBundle\Config\BitbucketConfig:
        arguments:
            $owner: '%bitbucket_owner%'
            $repo: '%bitbucket_repo%'

    AG\RepoStatusBundle\Command\CheckRepositoryStatusCommand:
        tags: ['console.command']

    AG\RepoStatusBundle\Service\RepositoryStatusChecker: ~

    AG\RepoStatusBundle\Client\GitHubClient: ~
