parameters:
    github.owner: '%env(GITHUB_OWNER)%'
    github.repo: '%env(GITHUB_REPO)%'
    github.api_base_url: '%env(GITHUB_API_BASE_URL)%'
    gitlab:
        owner: '%env(GITLAB_OWNER)%'
        repo: '%env(GITLAB_REPO)%'
    bitbucket:
        owner: '%env(BITBUCKET_OWNER)%'
        repo: '%env(BITBUCKET_REPO)%'
    slack.bot_token: '%env(SLACK_BOT_TOKEN)%'
    slack.channel: '%env(SLACK_CHANNEL)%'
    slack.api_base_url: '%env(SLACK_API_BASE_URL)%'
    default_vcs_author: '%env(DEFAULT_VCS_AUTHOR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $owner: null
            $repo: null

    App\RepoStatusBundle\Config\GitHubConfig:
        bind:
            $owner: '%github.owner%'
            $repo: '%github.repo%'

    App\RepoStatusBundle\Config\GitLabConfig:
        bind:
            $owner: '%gitlab.owner%'
            $repo: '%gitlab.repo%'

    App\RepoStatusBundle\Config\BitbucketConfig:
        bind:
            $owner: '%bitbucket.owner%'
            $repo: '%bitbucket.repo%'

    App\RepoStatusBundle\Service\RepositoryStatusChecker: ~

    App\RepoStatusBundle\Util\GitHubApiUrlBuilder:
        arguments:
            $baseUrl: '%github.api_base_url%'
            $config: '@App\RepoStatusBundle\Config\GitHubConfig'

    App\RepoStatusBundle\Client\GitHubClient: ~

    App\RepoStatusBundle\Client\BitbucketClient: ~

    App\RepoStatusBundle\Client\GitLabClient: ~

    App\RepoStatusBundle\Config\SlackConfig:
        arguments:
            $slackBotToken: '%slack.bot_token%'
            $slackChannel: '%slack.channel%'

    App\RepoStatusBundle\Util\SlackApiUrlBuilder:
        arguments:
            $slackApiBaseUrl: '%slack.api_base_url%'

    App\RepoStatusBundle\Service\MessageSender\SlackMessageSender:
        arguments:
            $httpClient: '@http_client'
            $urlBuilder: '@App\RepoStatusBundle\Util\SlackApiUrlBuilder'
            $config: '@App\RepoStatusBundle\Config\SlackConfig'

    App\RepoStatusBundle\Service\QuestionAsker: ~
