services:
    App\RepoStatusBundle\Config\GitHubConfig:
        arguments:
            $owner: '%github_owner%'
            $repo: '%github_repo%'

    App\RepoStatusBundle\Config\GitLabConfig:
        arguments:
            $owner: '%gitlab_owner%'
            $repo: '%gitlab_repo%'

    App\RepoStatusBundle\Config\BitbucketConfig:
        arguments:
            $owner: '%bitbucket_owner%'
            $repo: '%bitbucket_repo%'

    App\RepoStatusBundle\Command\CheckRepositoryStatusCommand:
        tags: ['console.command']

    App\RepoStatusBundle\Service\RepositoryStatusChecker: ~

    App\RepoStatusBundle\Util\GitHubApiUrlBuilder:
        arguments:
            $baseUrl: '%github_api_base_url%'
            $config: '@App\RepoStatusBundle\Config\GitHubConfig'

    App\RepoStatusBundle\Client\GitHubClient: ~

    App\RepoStatusBundle\Client\BitbucketClient:

    App\RepoStatusBundle\Client\GitLabClient: ~

    App\RepoStatusBundle\Config\SlackConfig:
        arguments:
            $slackBotToken: '%slack.bot_token%'
            $slackChannel: '%slack_channel%'

    App\RepoStatusBundle\Util\SlackApiUrlBuilder:
        arguments:
            $slackApiBaseUrl: '%slack.api_base_url%'

    App\RepoStatusBundle\Service\MessageSender\SlackMessageSender:
        arguments:
            $httpClient: '@http_client'
            $urlBuilder: '@App\RepoStatusBundle\Util\SlackApiUrlBuilder'
            $config: '@App\RepoStatusBundle\Config\SlackConfig'
